#!/usr/bin/env python
import argparse
import sys
import models
import copy
import heapq
from collections import namedtuple

parser = argparse.ArgumentParser(description='Simple phrase based decoder.')
parser.add_argument('-i', '--input', dest='input', default='data/input', help='File containing sentences to translate (default=data/input)')
parser.add_argument('-t', '--translation-model', dest='tm', default='data/tm', help='File containing translation model (default=data/tm)')
parser.add_argument('-s', '--stack-size', dest='s', default=5000, type=int, help='Maximum stack size (default=1)')
parser.add_argument('-n', '--num_sentences', dest='num_sents', default=sys.maxint, type=int, help='Number of sentences to decode (default=no limit)')
parser.add_argument('-l', '--language-model', dest='lm', default='data/lm', help='File containing ARPA-format language model (default=data/lm)')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', default=False,  help='Verbose mode (default=off)')
opts = parser.parse_args()

tm = models.TM(opts.tm, sys.maxint)
lm = models.LM(opts.lm)
sys.stderr.write('Decoding %s...\n' % (opts.input,))
input_sents = [tuple(line.strip().split()) for line in open(opts.input).readlines()[:opts.num_sents]]

hypothesis = namedtuple('hypothesis', 'logprob, lm_state, predecessor, phrase, coverage_vector')

def check_covered(coverage_vector, start, end):
    for start in xrange(start, end):
        if coverage_vector[start]:
            return False
    return True
    #for start in xrange(start, end):
    #    coverage_vector[start] = True
    #return True

def update_coverage_vector(current_coverage_vector, start, end):
    for start in xrange(start, end):
        current_coverage_vector[start] = True

mini = -sys.maxint
for f in input_sents:
    # The following code implements a DP monotone decoding
    # algorithm (one that doesn't permute the target phrases).
    # Hence all hypotheses in stacks[i] represent translations of 
    # the first i words of the input sentence.
    # HINT: Generalize this so that stacks[i] contains translations
    # of any i words (remember to keep track of which words those
    # are, and to estimate future costs)
    translation_scores = [[mini for j in xrange(len(f))] for i in xrange(len(f))]
    min_computational_costs = [[mini for j in xrange(len(f))] for i in xrange(len(f))]
    for i in xrange(len(f)):
        for j in xrange(i+1, len(f) + 1):
            if f[i:j] in tm:
                for phrase in tm[f[i:j]]:
                        translation_scores[i][j-1] = max(translation_scores[i][j-1], phrase.logprob)
    #print translation_scores 
    for i in xrange(len(f)):
        min_computational_costs[i][i] = translation_scores[i][i]
        
    for i in xrange(len(f)):
        k = 0
        j = i + 1
        while k < len(f) and j < len(f):
            min_computational_costs[k][j] = translation_scores[k][j]
            for m in xrange(k, j):                        
                if j >= len(f):
                    continue
                min_computational_costs[k][j] = max(min_computational_costs[k][j], min_computational_costs[k][m] + min_computational_costs[m+1][j])    
            k += 1
            j += 1
    initial_hypothesis = hypothesis(0.0, lm.begin(), None, None, [False for i in xrange(len(f) + 1)])
    temp = 0
    stacks = [{} for _ in f] + [{}]
    stacks[0][lm.begin()] = initial_hypothesis
    for i, stack in enumerate(stacks[:-1]):
        for h in heapq.nlargest(opts.s, stack.itervalues(), key=lambda h: h.logprob): # prune
            for j in xrange(len(f) + 1):
                for k in xrange(j + 1, len(f) + 1):
                    span = f[j:k]
                    if span in tm and check_covered(h.coverage_vector, j, k):
                        current_coverage_vector = copy.deepcopy(h.coverage_vector)
                        update_coverage_vector(current_coverage_vector, j, k)
                        temp = current_coverage_vector
                        #current_coverage_vector[j:k] = True
                        for phrase in tm[span]:
                            logprob = translation_scores[j][k-1]
                            logprob += h.logprob + phrase.logprob
                            lm_state = h.lm_state
                            for word in phrase.english.split():
                                (lm_state, word_logprob) = lm.score(lm_state, word)
                                logprob += word_logprob
                            logprob += lm.end(lm_state) if k == len(f) else 0.0
                            new_hypothesis = hypothesis(logprob, lm_state, h, phrase, current_coverage_vector)
                            index = i + k - j
                            if lm_state not in stacks[index] or stacks[index][lm_state].logprob < logprob: # second case is recombination
                                stacks[index][lm_state] = new_hypothesis
            
    # find best translation by looking at the best scoring hypothesis
    # on the last stack
    #try:
    winner = max(stacks[-1].itervalues(), key=lambda h: h.logprob)
    #print winner.logprob
    #except:
    #    print 'Error'
    #    pass
    def extract_english_recursive(h):
        return '' if h.predecessor is None else '%s%s ' % (extract_english_recursive(h.predecessor), h.phrase.english)
    print extract_english_recursive(winner)

    if opts.verbose:
        def extract_tm_logprob(h):
            return 0.0 if h.predecessor is None else h.phrase.logprob + extract_tm_logprob(h.predecessor)
        tm_logprob = extract_tm_logprob(winner)
        sys.stderr.write('LM = %f, TM = %f, Total = %f\n' % 
            (winner.logprob - tm_logprob, tm_logprob, winner.logprob))
